<?php

use Illuminate\Database\Seeder;

class paisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = array(
          array('id' => '1','iso' => 'AF','nombre' => 'Afganistán'),
          array('id' => '2','iso' => 'AX','nombre' => 'Islas Gland'),
          array('id' => '3','iso' => 'AL','nombre' => 'Albania'),
          array('id' => '4','iso' => 'DE','nombre' => 'Alemania'),
          array('id' => '5','iso' => 'AD','nombre' => 'Andorra'),
          array('id' => '6','iso' => 'AO','nombre' => 'Angola'),
          array('id' => '7','iso' => 'AI','nombre' => 'Anguilla'),
          array('id' => '8','iso' => 'AQ','nombre' => 'Antártida'),
          array('id' => '9','iso' => 'AG','nombre' => 'Antigua y Barbuda'),
          array('id' => '10','iso' => 'AN','nombre' => 'Antillas Holandesas'),
          array('id' => '11','iso' => 'SA','nombre' => 'Arabia Saudí'),
          array('id' => '12','iso' => 'DZ','nombre' => 'Argelia'),
          array('id' => '13','iso' => 'AR','nombre' => 'Argentina'),
          array('id' => '14','iso' => 'AM','nombre' => 'Armenia'),
          array('id' => '15','iso' => 'AW','nombre' => 'Aruba'),
          array('id' => '16','iso' => 'AU','nombre' => 'Australia'),
          array('id' => '17','iso' => 'AT','nombre' => 'Austria'),
          array('id' => '18','iso' => 'AZ','nombre' => 'Azerbaiyán'),
          array('id' => '19','iso' => 'BS','nombre' => 'Bahamas'),
          array('id' => '20','iso' => 'BH','nombre' => 'Bahréin'),
          array('id' => '21','iso' => 'BD','nombre' => 'Bangladesh'),
          array('id' => '22','iso' => 'BB','nombre' => 'Barbados'),
          array('id' => '23','iso' => 'BY','nombre' => 'Bielorrusia'),
          array('id' => '24','iso' => 'BE','nombre' => 'Bélgica'),
          array('id' => '25','iso' => 'BZ','nombre' => 'Belice'),
          array('id' => '26','iso' => 'BJ','nombre' => 'Benin'),
          array('id' => '27','iso' => 'BM','nombre' => 'Bermudas'),
          array('id' => '28','iso' => 'BT','nombre' => 'Bhután'),
          array('id' => '29','iso' => 'BO','nombre' => 'Bolivia'),
          array('id' => '30','iso' => 'BA','nombre' => 'Bosnia y Herzegovina'),
          array('id' => '31','iso' => 'BW','nombre' => 'Botsuana'),
          array('id' => '32','iso' => 'BV','nombre' => 'Isla Bouvet'),
          array('id' => '33','iso' => 'BR','nombre' => 'Brasil'),
          array('id' => '34','iso' => 'BN','nombre' => 'Brunéi'),
          array('id' => '35','iso' => 'BG','nombre' => 'Bulgaria'),
          array('id' => '36','iso' => 'BF','nombre' => 'Burkina Faso'),
          array('id' => '37','iso' => 'BI','nombre' => 'Burundi'),
          array('id' => '38','iso' => 'CV','nombre' => 'Cabo Verde'),
          array('id' => '39','iso' => 'KY','nombre' => 'Islas Caimán'),
          array('id' => '40','iso' => 'KH','nombre' => 'Camboya'),
          array('id' => '41','iso' => 'CM','nombre' => 'Camerún'),
          array('id' => '42','iso' => 'CA','nombre' => 'Canadá'),
          array('id' => '43','iso' => 'CF','nombre' => 'República Centroafricana'),
          array('id' => '44','iso' => 'TD','nombre' => 'Chad'),
          array('id' => '45','iso' => 'CZ','nombre' => 'República Checa'),
          array('id' => '46','iso' => 'CL','nombre' => 'Chile'),
          array('id' => '47','iso' => 'CN','nombre' => 'China'),
          array('id' => '48','iso' => 'CY','nombre' => 'Chipre'),
          array('id' => '49','iso' => 'CX','nombre' => 'Isla de Navidad'),
          array('id' => '50','iso' => 'VA','nombre' => 'Ciudad del Vaticano'),
          array('id' => '51','iso' => 'CC','nombre' => 'Islas Cocos'),
          array('id' => '52','iso' => 'CO','nombre' => 'Colombia'),
          array('id' => '53','iso' => 'KM','nombre' => 'Comoras'),
          array('id' => '54','iso' => 'CD','nombre' => 'República Democrática del Congo'),
          array('id' => '55','iso' => 'CG','nombre' => 'Congo'),
          array('id' => '56','iso' => 'CK','nombre' => 'Islas Cook'),
          array('id' => '57','iso' => 'KP','nombre' => 'Corea del Norte'),
          array('id' => '58','iso' => 'KR','nombre' => 'Corea del Sur'),
          array('id' => '59','iso' => 'CI','nombre' => 'Costa de Marfil'),
          array('id' => '60','iso' => 'CR','nombre' => 'Costa Rica'),
          array('id' => '61','iso' => 'HR','nombre' => 'Croacia'),
          array('id' => '62','iso' => 'CU','nombre' => 'Cuba'),
          array('id' => '63','iso' => 'DK','nombre' => 'Dinamarca'),
          array('id' => '64','iso' => 'DM','nombre' => 'Dominica'),
          array('id' => '65','iso' => 'DO','nombre' => 'República Dominicana'),
          array('id' => '66','iso' => 'EC','nombre' => 'Ecuador'),
          array('id' => '67','iso' => 'EG','nombre' => 'Egipto'),
          array('id' => '68','iso' => 'SV','nombre' => 'El Salvador'),
          array('id' => '69','iso' => 'AE','nombre' => 'Emiratos Árabes Unidos'),
          array('id' => '70','iso' => 'ER','nombre' => 'Eritrea'),
          array('id' => '71','iso' => 'SK','nombre' => 'Eslovaquia'),
          array('id' => '72','iso' => 'SI','nombre' => 'Eslovenia'),
          array('id' => '73','iso' => 'ES','nombre' => 'España'),
          array('id' => '74','iso' => 'UM','nombre' => 'Islas ultramarinas de Estados Unidos'),
          array('id' => '75','iso' => 'US','nombre' => 'Estados Unidos'),
          array('id' => '76','iso' => 'EE','nombre' => 'Estonia'),
          array('id' => '77','iso' => 'ET','nombre' => 'Etiopía'),
          array('id' => '78','iso' => 'FO','nombre' => 'Islas Feroe'),
          array('id' => '79','iso' => 'PH','nombre' => 'Filipinas'),
          array('id' => '80','iso' => 'FI','nombre' => 'Finlandia'),
          array('id' => '81','iso' => 'FJ','nombre' => 'Fiyi'),
          array('id' => '82','iso' => 'FR','nombre' => 'Francia'),
          array('id' => '83','iso' => 'GA','nombre' => 'Gabón'),
          array('id' => '84','iso' => 'GM','nombre' => 'Gambia'),
          array('id' => '85','iso' => 'GE','nombre' => 'Georgia'),
          array('id' => '86','iso' => 'GS','nombre' => 'Islas Georgias del Sur y Sandwich del Sur'),
          array('id' => '87','iso' => 'GH','nombre' => 'Ghana'),
          array('id' => '88','iso' => 'GI','nombre' => 'Gibraltar'),
          array('id' => '89','iso' => 'GD','nombre' => 'Granada'),
          array('id' => '90','iso' => 'GR','nombre' => 'Grecia'),
          array('id' => '91','iso' => 'GL','nombre' => 'Groenlandia'),
          array('id' => '92','iso' => 'GP','nombre' => 'Guadalupe'),
          array('id' => '93','iso' => 'GU','nombre' => 'Guam'),
          array('id' => '94','iso' => 'GT','nombre' => 'Guatemala'),
          array('id' => '95','iso' => 'GF','nombre' => 'Guayana Francesa'),
          array('id' => '96','iso' => 'GN','nombre' => 'Guinea'),
          array('id' => '97','iso' => 'GQ','nombre' => 'Guinea Ecuatorial'),
          array('id' => '98','iso' => 'GW','nombre' => 'Guinea-Bissau'),
          array('id' => '99','iso' => 'GY','nombre' => 'Guyana'),
          array('id' => '100','iso' => 'HT','nombre' => 'Haití'),
          array('id' => '101','iso' => 'HM','nombre' => 'Islas Heard y McDonald'),
          array('id' => '102','iso' => 'HN','nombre' => 'Honduras'),
          array('id' => '103','iso' => 'HK','nombre' => 'Hong Kong'),
          array('id' => '104','iso' => 'HU','nombre' => 'Hungría'),
          array('id' => '105','iso' => 'IN','nombre' => 'India'),
          array('id' => '106','iso' => 'ID','nombre' => 'Indonesia'),
          array('id' => '107','iso' => 'IR','nombre' => 'Irán'),
          array('id' => '108','iso' => 'IQ','nombre' => 'Iraq'),
          array('id' => '109','iso' => 'IE','nombre' => 'Irlanda'),
          array('id' => '110','iso' => 'IS','nombre' => 'Islandia'),
          array('id' => '111','iso' => 'IL','nombre' => 'Israel'),
          array('id' => '112','iso' => 'IT','nombre' => 'Italia'),
          array('id' => '113','iso' => 'JM','nombre' => 'Jamaica'),
          array('id' => '114','iso' => 'JP','nombre' => 'Japón'),
          array('id' => '115','iso' => 'JO','nombre' => 'Jordania'),
          array('id' => '116','iso' => 'KZ','nombre' => 'Kazajstán'),
          array('id' => '117','iso' => 'KE','nombre' => 'Kenia'),
          array('id' => '118','iso' => 'KG','nombre' => 'Kirguistán'),
          array('id' => '119','iso' => 'KI','nombre' => 'Kiribati'),
          array('id' => '120','iso' => 'KW','nombre' => 'Kuwait'),
          array('id' => '121','iso' => 'LA','nombre' => 'Laos'),
          array('id' => '122','iso' => 'LS','nombre' => 'Lesotho'),
          array('id' => '123','iso' => 'LV','nombre' => 'Letonia'),
          array('id' => '124','iso' => 'LB','nombre' => 'Líbano'),
          array('id' => '125','iso' => 'LR','nombre' => 'Liberia'),
          array('id' => '126','iso' => 'LY','nombre' => 'Libia'),
          array('id' => '127','iso' => 'LI','nombre' => 'Liechtenstein'),
          array('id' => '128','iso' => 'LT','nombre' => 'Lituania'),
          array('id' => '129','iso' => 'LU','nombre' => 'Luxemburgo'),
          array('id' => '130','iso' => 'MO','nombre' => 'Macao'),
          array('id' => '131','iso' => 'MK','nombre' => 'ARY Macedonia'),
          array('id' => '132','iso' => 'MG','nombre' => 'Madagascar'),
          array('id' => '133','iso' => 'MY','nombre' => 'Malasia'),
          array('id' => '134','iso' => 'MW','nombre' => 'Malawi'),
          array('id' => '135','iso' => 'MV','nombre' => 'Maldivas'),
          array('id' => '136','iso' => 'ML','nombre' => 'Malí'),
          array('id' => '137','iso' => 'MT','nombre' => 'Malta'),
          array('id' => '138','iso' => 'FK','nombre' => 'Islas Malvinas'),
          array('id' => '139','iso' => 'MP','nombre' => 'Islas Marianas del Norte'),
          array('id' => '140','iso' => 'MA','nombre' => 'Marruecos'),
          array('id' => '141','iso' => 'MH','nombre' => 'Islas Marshall'),
          array('id' => '142','iso' => 'MQ','nombre' => 'Martinica'),
          array('id' => '143','iso' => 'MU','nombre' => 'Mauricio'),
          array('id' => '144','iso' => 'MR','nombre' => 'Mauritania'),
          array('id' => '145','iso' => 'YT','nombre' => 'Mayotte'),
          array('id' => '146','iso' => 'MX','nombre' => 'México'),
          array('id' => '147','iso' => 'FM','nombre' => 'Micronesia'),
          array('id' => '148','iso' => 'MD','nombre' => 'Moldavia'),
          array('id' => '149','iso' => 'MC','nombre' => 'Mónaco'),
          array('id' => '150','iso' => 'MN','nombre' => 'Mongolia'),
          array('id' => '151','iso' => 'MS','nombre' => 'Montserrat'),
          array('id' => '152','iso' => 'MZ','nombre' => 'Mozambique'),
          array('id' => '153','iso' => 'MM','nombre' => 'Myanmar'),
          array('id' => '154','iso' => 'NA','nombre' => 'Namibia'),
          array('id' => '155','iso' => 'NR','nombre' => 'Nauru'),
          array('id' => '156','iso' => 'NP','nombre' => 'Nepal'),
          array('id' => '157','iso' => 'NI','nombre' => 'Nicaragua'),
          array('id' => '158','iso' => 'NE','nombre' => 'Níger'),
          array('id' => '159','iso' => 'NG','nombre' => 'Nigeria'),
          array('id' => '160','iso' => 'NU','nombre' => 'Niue'),
          array('id' => '161','iso' => 'NF','nombre' => 'Isla Norfolk'),
          array('id' => '162','iso' => 'NO','nombre' => 'Noruega'),
          array('id' => '163','iso' => 'NC','nombre' => 'Nueva Caledonia'),
          array('id' => '164','iso' => 'NZ','nombre' => 'Nueva Zelanda'),
          array('id' => '165','iso' => 'OM','nombre' => 'Omán'),
          array('id' => '166','iso' => 'NL','nombre' => 'Países Bajos'),
          array('id' => '167','iso' => 'PK','nombre' => 'Pakistán'),
          array('id' => '168','iso' => 'PW','nombre' => 'Palau'),
          array('id' => '169','iso' => 'PS','nombre' => 'Palestina'),
          array('id' => '170','iso' => 'PA','nombre' => 'Panamá'),
          array('id' => '171','iso' => 'PG','nombre' => 'Papúa Nueva Guinea'),
          array('id' => '172','iso' => 'PY','nombre' => 'Paraguay'),
          array('id' => '173','iso' => 'PE','nombre' => 'Perú'),
          array('id' => '174','iso' => 'PN','nombre' => 'Islas Pitcairn'),
          array('id' => '175','iso' => 'PF','nombre' => 'Polinesia Francesa'),
          array('id' => '176','iso' => 'PL','nombre' => 'Polonia'),
          array('id' => '177','iso' => 'PT','nombre' => 'Portugal'),
          array('id' => '178','iso' => 'PR','nombre' => 'Puerto Rico'),
          array('id' => '179','iso' => 'QA','nombre' => 'Qatar'),
          array('id' => '180','iso' => 'GB','nombre' => 'Reino Unido'),
          array('id' => '181','iso' => 'RE','nombre' => 'Reunión'),
          array('id' => '182','iso' => 'RW','nombre' => 'Ruanda'),
          array('id' => '183','iso' => 'RO','nombre' => 'Rumania'),
          array('id' => '184','iso' => 'RU','nombre' => 'Rusia'),
          array('id' => '185','iso' => 'EH','nombre' => 'Sahara Occidental'),
          array('id' => '186','iso' => 'SB','nombre' => 'Islas Salomón'),
          array('id' => '187','iso' => 'WS','nombre' => 'Samoa'),
          array('id' => '188','iso' => 'AS','nombre' => 'Samoa Americana'),
          array('id' => '189','iso' => 'KN','nombre' => 'San Cristóbal y Nevis'),
          array('id' => '190','iso' => 'SM','nombre' => 'San Marino'),
          array('id' => '191','iso' => 'PM','nombre' => 'San Pedro y Miquelón'),
          array('id' => '192','iso' => 'VC','nombre' => 'San Vicente y las Granadinas'),
          array('id' => '193','iso' => 'SH','nombre' => 'Santa Helena'),
          array('id' => '194','iso' => 'LC','nombre' => 'Santa Lucía'),
          array('id' => '195','iso' => 'ST','nombre' => 'Santo Tomé y Príncipe'),
          array('id' => '196','iso' => 'SN','nombre' => 'Senegal'),
          array('id' => '197','iso' => 'CS','nombre' => 'Serbia y Montenegro'),
          array('id' => '198','iso' => 'SC','nombre' => 'Seychelles'),
          array('id' => '199','iso' => 'SL','nombre' => 'Sierra Leona'),
          array('id' => '200','iso' => 'SG','nombre' => 'Singapur'),
          array('id' => '201','iso' => 'SY','nombre' => 'Siria'),
          array('id' => '202','iso' => 'SO','nombre' => 'Somalia'),
          array('id' => '203','iso' => 'LK','nombre' => 'Sri Lanka'),
          array('id' => '204','iso' => 'SZ','nombre' => 'Suazilandia'),
          array('id' => '205','iso' => 'ZA','nombre' => 'Sudáfrica'),
          array('id' => '206','iso' => 'SD','nombre' => 'Sudán'),
          array('id' => '207','iso' => 'SE','nombre' => 'Suecia'),
          array('id' => '208','iso' => 'CH','nombre' => 'Suiza'),
          array('id' => '209','iso' => 'SR','nombre' => 'Surinam'),
          array('id' => '210','iso' => 'SJ','nombre' => 'Svalbard y Jan Mayen'),
          array('id' => '211','iso' => 'TH','nombre' => 'Tailandia'),
          array('id' => '212','iso' => 'TW','nombre' => 'Taiwán'),
          array('id' => '213','iso' => 'TZ','nombre' => 'Tanzania'),
          array('id' => '214','iso' => 'TJ','nombre' => 'Tayikistán'),
          array('id' => '215','iso' => 'IO','nombre' => 'Territorio Británico del Océano Índico'),
          array('id' => '216','iso' => 'TF','nombre' => 'Territorios Australes Franceses'),
          array('id' => '217','iso' => 'TL','nombre' => 'Timor Oriental'),
          array('id' => '218','iso' => 'TG','nombre' => 'Togo'),
          array('id' => '219','iso' => 'TK','nombre' => 'Tokelau'),
          array('id' => '220','iso' => 'TO','nombre' => 'Tonga'),
          array('id' => '221','iso' => 'TT','nombre' => 'Trinidad y Tobago'),
          array('id' => '222','iso' => 'TN','nombre' => 'Túnez'),
          array('id' => '223','iso' => 'TC','nombre' => 'Islas Turcas y Caicos'),
          array('id' => '224','iso' => 'TM','nombre' => 'Turkmenistán'),
          array('id' => '225','iso' => 'TR','nombre' => 'Turquía'),
          array('id' => '226','iso' => 'TV','nombre' => 'Tuvalu'),
          array('id' => '227','iso' => 'UA','nombre' => 'Ucrania'),
          array('id' => '228','iso' => 'UG','nombre' => 'Uganda'),
          array('id' => '229','iso' => 'UY','nombre' => 'Uruguay'),
          array('id' => '230','iso' => 'UZ','nombre' => 'Uzbekistán'),
          array('id' => '231','iso' => 'VU','nombre' => 'Vanuatu'),
          array('id' => '232','iso' => 'VE','nombre' => 'Venezuela'),
          array('id' => '233','iso' => 'VN','nombre' => 'Vietnam'),
          array('id' => '234','iso' => 'VG','nombre' => 'Islas Vírgenes Británicas'),
          array('id' => '235','iso' => 'VI','nombre' => 'Islas Vírgenes de los Estados Unidos'),
          array('id' => '236','iso' => 'WF','nombre' => 'Wallis y Futuna'),
          array('id' => '237','iso' => 'YE','nombre' => 'Yemen'),
          array('id' => '238','iso' => 'DJ','nombre' => 'Yibuti'),
          array('id' => '239','iso' => 'ZM','nombre' => 'Zambia'),
          array('id' => '240','iso' => 'ZW','nombre' => 'Zimbabue')
        );

		foreach($paises as $pais){
            DB::table('paises')->insert(array(
            	'id' => $pais['id'],
              	'name' => $pais['nombre'],
              	'iso' => $pais['iso'],
            
            ));
        }
    }
}
